### ISSUE TITLE
Statically link vcredist

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/rust-g#97]
We faced issues with a few people where they couldn't use even old copies of rust-g because of obscure "The specific procedure could not be found" errors. Eventually they had to install vcredist AND restart their computer before it was fixed.

We should statically link vcredist to stop errors like these.

You just need this in .cargo/config.toml:

```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
```

(Also reminder to fix #86)

**Comment by willox** [comment]
```toml
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
```

:)
